### ISSUE TITLE
Minor Fixes 🛠 

### ISSUE THREAD

**Issue by ArnabBiswas2303** [NinjaAadi/Github-Commands#2]
- [ ] No quotation around creating branch name command, add remote repository command.
- [ ] What is the difference between git fetch and git pull has logical error on line 2.
- [ ] Remove the word origin from the command to pull the changes.

**Comment by ArnabBiswas2303** [comment]
@NinjaAadi I would like to work on this. Please assign this to me.

**Comment by NinjaAadi** [comment]
Assigned to you. Good luck
